version: '2'

services:
  app:
    image: 'back:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
    ports:
      - "8081:8081"

  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_PASSWORD=root