version: '3.7'

services:
  back:
    image: 'cr.yandex/crpdfuj6ilffi9dkqfts/spice_back:latest'
    build:
      context: .
    container_name: back
    depends_on:
      - db
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      MINIO_ROOT_USER: adminminio
      MINIO_ROOT_PASSWORD: adminminio
      MINIO_BUCKET_NAME: bucket
      MINIO_URL: http://minio:9000
    ports:
      - "8081:8081"

  ui:
    image: 'cr.yandex/crpdfuj6ilffi9dkqfts/spice_ui:latest'
    container_name: ui
    ports:
      - "8080:8080"

  db:
    image: 'postgres:latest'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: adminminio
      MINIO_ROOT_PASSWORD: adminminio
    command: server /data --console-address ":9001"
