spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
server:
  port: 8081


minio:
  url: ${MINIO_URL:http://localhost:9000}
  user: ${MINIO_ROOT_USER:adminminio}
  password: ${MINIO_ROOT_PASSWORD:adminminio}
  bucket: ${MINIO_BUCKET_NAME:bucket}