CREATE TABLE model
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    manufacturer   VARCHAR(255),
    max_i          DOUBLE PRECISION,
    max_u          DOUBLE PRECISION,
    max_prob_u     DOUBLE PRECISION,
    max_p          DOUBLE PRECISION,
    box            VARCHAR(255),
    use_conditions VARCHAR(255),
    tech_link      VARCHAR(255),
    link           VARCHAR(255),
    CONSTRAINT pk_model PRIMARY KEY (id)
);

CREATE TABLE file
(
    id        UUID NOT NULL,
    file_name VARCHAR(255),
    CONSTRAINT pk_file PRIMARY KEY (id)
);

CREATE TABLE request
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fio        VARCHAR(255),
    org        VARCHAR(255),
    email      VARCHAR(255),
    phone      VARCHAR(255),
    type       VARCHAR(255),
    comment    VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_request PRIMARY KEY (id)
);