CREATE TABLE model
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    manufacturer   VARCHAR(255),
    max_i          DOUBLE PRECISION,
    max_u          DOUBLE PRECISION,
    max_prob_u     DOUBLE PRECISION,
    max_p          DOUBLE PRECISION,
    box            VARCHAR(255),
    use_conditions VARCHAR(255),
    tech_link      VARCHAR(255),
    link           VARCHAR(255),
    CONSTRAINT pk_model PRIMARY KEY (id)
);